In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [3]:
# Write your code here
a =  np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])

b = np.exp(-np.logaddexp(0, -a[-5:]))

display(b)




array([0.549834  , 0.47502081, 0.52497919, 0.68997448, 0.4378235 ])

**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (y.reshape(-1, 1), the alternative y.T will not work because T does not work on 1D arrays).

In [4]:
# Write your code here
x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])


print(np.sum(np.multiply(x, y)))
print(np.dot(x, y))
print(np.matmul(x, y.reshape(-1,1))[0])


225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [52]:
# Write your code here
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2])
zero = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])

y = 1 / ( 1 + np.exp(np.sum(np.multiply(np.negative(x[:x.size]), zero[:x.size]))- zero[-1]) )
print(np.round(y, 8))

0.24176998


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [77]:
# Write your code here

A = np.array([[1, 2, 1], [3, 0, 1]])
B = np.array([[0.2], [0.3]])

x = np.array([1,2,3]).reshape(3,1)

y = np.dot(A,x) + B


print(y)


[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [22]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

display(steam_df)

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

user-id                  game-title behavior-name  value  zero
0       151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1       151603712  The Elder Scrolls V Skyrim          play  273.0     0
2       151603712                   Fallout 4      purchase    1.0     0
3       151603712                   Fallout 4          play   87.0     0
4       151603712                       Spore      purchase    1.0     0
...           ...                         ...           ...    ...   ...
199995  128470551                 Titan Souls          play    1.5     0
199996  128470551  Grand Theft Auto Vice City      purchase    1.0     0
199997  128470551  Grand Theft Auto Vice City          play    1.5     0
199998  128470551                        RUSH      purchase    1.0     0
199999  128470551                        RUSH          play    1.4     0

[200000 rows x 5 columns]

## Merge both MovieLens DataFrames into one

In [6]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [7]:
# Write your code here
st = steam_df.loc[steam_df['behavior-name'] == 'purchase']

st = st.groupby('user-id').sum()
print(len(st.index))


12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [124]:
# Write your code here
st = steam_df.loc[steam_df['behavior-name'] == 'purchase']
st = st.groupby('user-id').size().to_frame('size')


print(st['size'].mean())


10.45033486645687


**Task 7.** How many purchases people made on average?

In [126]:
# Write your code here
st = steam_df.loc[steam_df['behavior-name'] == 'purchase']
st = st.groupby('user-id').size().to_frame('size')


print(st['size'].mean())


10.45033486645687


**Task 8.** Who bought the most games?

In [146]:
# Write your code here
st = steam_df.loc[steam_df['behavior-name'] == 'purchase']
st = st.groupby('user-id').size().to_frame('size').reset_index().sort_values('size', ascending=False)


print(st.head(1)['user-id'].iloc[0])

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [169]:
# Write your code here
# Write your code here
st = steam_df.loc[steam_df['behavior-name'] == 'play']
st = st.loc[steam_df['game-title'] == 'The Elder Scrolls V Skyrim']
st.groupby('user-id')

print(np.round(st['value'].mean(), 2))





104.71


**Task 10.** Which games were played the most (in terms of the number of hours played)? Display a DataFrame with the first 10 titles and respective numbers of hours.

In [68]:
# Write your code here

steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'play']
steam_grouped = steam_grouped[['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').sum().sort_values(by='value', ascending=False).reset_index()

print(steam_grouped.head(10))






                        game-title        value
0                           Dota 2  2426.570020
1                  Team Fortress 2  1164.412133
2  Counter-Strike Global Offensive   690.227416
3                         Unturned   535.839806
4                    Left 4 Dead 2   401.504096
5            Counter-Strike Source   358.396551
6       The Elder Scrolls V Skyrim   339.349065
7                      Garry's Mod   333.835037
8                   Counter-Strike   284.712259
9       Sid Meier's Civilization V   277.694780


**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print a DataFrame with the first 10 titles and respective numbers of hours.

In [71]:
# Write your code here
st = steam_df.loc[steam_df['behavior-name'] == 'play']
st = st[['game-title', 'value']]
st = st.groupby('game-title').mean().sort_values(by='value', ascending=False).reset_index()
print(st.head(10))

                                       game-title     value
0                         Eastside Hockey Manager  0.501256
1                                 FIFA Manager 09  0.501256
2                               Freaking Meatbags  0.501256
3                   Worldwide Soccer Manager 2009  0.501256
4  NOBUNAGA'S AMBITION Kakushin with Power Up Kit  0.501256
5                                 FIFA Manager 11  0.501256
6                                        MLB 2K10  0.501256
7                                       Avernum 4  0.501256
8                                       Avernum 5  0.501256
9                            Cultures - Northland  0.501255


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [55]:
# Write your code here
task_12_df = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['game-title', 'user-id']]
task_12_df_grouped = steam_df.loc[steam_df['behavior-name'] == 'play', ['game-title', 'user-id', 'value']]

task_12_df_grouped = pd.merge(task_12_df_grouped, task_12_df, on=['game-title', 'user-id'], how='left').fillna(0)
task_12_df_grouped = task_12_df_grouped.loc[:, ['game-title', 'value']]
task_12_df_grouped = task_12_df_grouped.groupby('game-title').mean().sort_values(by='value', ascending=False).reset_index()

print(task_12_df_grouped.head(10))

                                       game-title     value
0                         Eastside Hockey Manager  0.501256
1                                 FIFA Manager 09  0.501256
2                               Freaking Meatbags  0.501256
3                   Worldwide Soccer Manager 2009  0.501256
4  NOBUNAGA'S AMBITION Kakushin with Power Up Kit  0.501256
5                                 FIFA Manager 11  0.501256
6                                        MLB 2K10  0.501256
7                                       Avernum 4  0.501256
8                                       Avernum 5  0.501256
9                            Cultures - Northland  0.501255


**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print a DataFrame with the first 10 rows from the entire Steam dataset after this change.

In [27]:
# Write your code here
def f(x):
    return 1/(1 + np.exp(-x/100))

condition = steam_df['behavior-name'] == 'play'
steam_df.loc[condition, 'value'] =  steam_df.loc[condition, 'value'].apply(f)
print(steam_df.head(10))

     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.501256     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.501254     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.501253     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.501253     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.501253     0


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [87]:
# Write your code here
# ml_movies_df_copy = ml_df.copy()

# ml_movies_df_copy["genres"]= ml_movies_df_copy["genres"].str.split("|").explode('genres')
# display(ml_movies_df_copy.groupby('movieId')['userId'].count().reset_index(name='userIdCount'))



# display(ml_movies_df_copy)

# display(ml_movies_df_copy.value_counts().to_frame('size').reset_index().sort_values('size', ascending=False).head(10))

ml_df_copy = ml_df.copy()
genres = set("|".join(ml_df['genres'].tolist()).split("|"))

import warnings
warnings.filterwarnings("ignore", 'This pattern has match groups')
popularity = {}
for genre in genres:
    popularity[genre] = ml_df['genres'].str.contains(genre).sum()

# Transform the dict into a DataFrame for nicer print
popularity = pd.DataFrame.from_dict(popularity, columns=['n_users'], orient='index')

# Sort by popularity
popularity = popularity.sort_values(by='n_users', ascending=False)

# Make the genre a column instead of an index
popularity = popularity.reset_index().rename(columns={'index':'genre'})

print(popularity)

                 genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47


**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [ ]:
# Write your code here


**Task 16.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print a DataFrame with the first 10 in the form: title, average rating, bias.

In [95]:
# Write your code here

ml_test = ml_df[['title', 'rating']]
ml_test = ml_test.groupby('title').mean().reset_index()
ml_test = ml_test.rename(columns={'rating': 'average_rating'})
average = ml_df['rating'].mean()
ml_test['bias'] = ml_test['average_rating'] - average

print(ml_test.head(10))

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print a DataFrame with the first 10 in the form: user_id, average rating, bias.

In [98]:
# Write your code here

ml_test = ml_df[['userId', 'rating']]
ml_test = ml_test.groupby('userId').mean().reset_index()
ml_test = ml_test.rename(columns={'userId': 'user_id', 'rating': 'average_rating'})
average = ml_df['rating'].mean()
ml_test['bias'] = ml_test['average_rating'] - average

print(ml_test.head(10))

   user_id  average_rating      bias
0        1        4.366379  0.864822
1        2        3.948276  0.446719
2        3        2.435897 -1.065660
3        4        3.555556  0.053999
4        5        3.636364  0.134807
5        6        3.493631 -0.007926
6        7        3.230263 -0.271294
7        8        3.574468  0.072911
8        9        3.260870 -0.240687
9       10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task. Alternatively, try using the DataFrame pivot and reindex methods and compare the execution time. Initialize the numpy random number generator with seed=4321.

In [108]:
# Write your code here
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))


movies_table = pd.DataFrame(np.array(movie_ids).reshape(-1, 1), columns=['movieId'])
movies_table = movies_table.merge(ml_movies_df, on=['movieId'])

given_interactions = ml_df.loc[ml_df['userId'].isin(user_ids)].copy()
given_interactions = ml_df.loc[ml_df['movieId'].isin(movie_ids)].copy()
given_interactions['value'] = 1

interactions = given_interactions.pivot(index='userId', columns='title', values='value')
interactions = interactions.rename_axis(None).rename_axis(None, axis=1)
interactions = interactions.reindex(user_ids)
interactions = interactions.reindex(movies_table['title'].values, axis='columns')
interactions = interactions.fillna(0)

print(interactions_df)



     Father of the Bride (1950)  Matrix, The (1999)  Howards End (1992)  \
11                          0.0                 0.0                 0.0   
277                         0.0                 0.0                 0.0   
286                         0.0                 1.0                 0.0   
357                         0.0                 0.0                 0.0   
414                         0.0                 1.0                 0.0   
428                         0.0                 1.0                 0.0   
470                         0.0                 0.0                 0.0   
487                         0.0                 1.0                 0.0   
543                         0.0                 1.0                 0.0   
544                         0.0                 0.0                 0.0   

     Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 0.0                         
277           

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix (2D numpy array) for the MovieLens dataset. Print the submatrix of the first 10 rows and 10 columns.

In [123]:
# Write your code here
interaction_matrix = np.zeros(shape=(ml_df['userId'].max() + 1, ml_df['movieId'].max() + 1))
for ids, row in ml_df.iterrows():
    interaction_matrix[(row['userId'],row['movieId'])] = 1

print(interaction_matrix[:10, :10])


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Use a single matrix multiplication to obtain the result. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. Use a single matrix multiplication to obtain the result. To prevent memory error use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here
